#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_DIR"

SMOKE_DIR="$PROJECT_DIR/build/smoke"
SCHEME="Chapterly"
PROJECT="Chapterly.xcodeproj"
BUNDLE_ID="dev.chapterly.Chapterly"

mkdir -p "$SMOKE_DIR"

# Clear previous preflight outputs
: > "$SMOKE_DIR/preflight.log"
: > "$SMOKE_DIR/preflight-report.md"

log() { echo "$*" | tee -a "$SMOKE_DIR/preflight.log"; }
fail_report() {
  {
    echo "# Preflight Failed"
    echo ""
    echo "**Phase:** $1"
    echo ""
    echo "## Error"
    echo ""
    echo "$2"
    echo ""
    echo "## Possible Causes"
    echo ""
    echo "$3"
    echo ""
    echo "## Next Steps"
    echo ""
    echo "$4"
    echo ""
    echo "---"
    echo "*Generated by smoke-diagnostics.sh at $(date)*"
  } > "$SMOKE_DIR/preflight-report.md"
  log "FAIL: Preflight report written to $SMOKE_DIR/preflight-report.md"
  exit 1
}

# ============================================================
# PREFLIGHT PHASE
# ============================================================
log "=== Preflight Checks ==="
log "Date: $(date)"
log "Project: $PROJECT_DIR"
log ""
PREFLIGHT_OK=true

# --- 1. Basic tools ---
log "--- Check: Xcode toolchain ---"

XCODE_PATH=$(xcode-select -p 2>&1) || true
log "xcode-select -p: $XCODE_PATH"
if [ ! -d "$XCODE_PATH" ]; then
  fail_report "Xcode toolchain" \
    "xcode-select path does not exist: $XCODE_PATH" \
    "- Xcode is not installed
- Command Line Tools not installed
- Wrong Xcode path selected" \
    "Run: \`xcode-select --install\` or \`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer\`"
fi

XCODEBUILD_VER=$(xcodebuild -version 2>&1 | head -2) || true
log "xcodebuild -version: $XCODEBUILD_VER"

XCRUN_VER=$(xcrun --version 2>&1) || true
log "xcrun --version: $XCRUN_VER"

# --- 2. XcodeGen check ---
log ""
log "--- Check: Project generation ---"

NEEDS_XCODEGEN=false
if [ -f "$PROJECT_DIR/project.yml" ]; then
  NEEDS_XCODEGEN=true
  log "Found project.yml — this is an XcodeGen project"

  if ! command -v xcodegen &>/dev/null; then
    fail_report "XcodeGen" \
      "project.yml exists but xcodegen command not found" \
      "- XcodeGen is not installed
- XcodeGen is not in PATH
- Homebrew bin not in PATH" \
      "Install: \`brew install xcodegen\`"
  fi

  XCODEGEN_VER=$(xcodegen --version 2>&1) || true
  log "xcodegen --version: $XCODEGEN_VER"

  log "Running: xcodegen generate"
  if ! xcodegen generate --spec "$PROJECT_DIR/project.yml" \
       > "$SMOKE_DIR/xcodegen.log" 2>&1; then
    XCODEGEN_ERR=$(cat "$SMOKE_DIR/xcodegen.log")
    log "xcodegen generate FAILED"
    log "Output saved to $SMOKE_DIR/xcodegen.log"

    CAUSES="- project.yml syntax error (bad YAML indentation, missing colon, wrong type)
- Source path in project.yml does not exist on disk (e.g. \`sources: [App]\` but no App/ directory)
- Target name mismatch between project.yml and actual files
- Package dependency path or URL is wrong
- XcodeGen version incompatible with project.yml spec version
- Missing Info.plist at the path specified in project.yml"

    # Try to detect specific error patterns
    HINTS=""
    if echo "$XCODEGEN_ERR" | grep -qi "not found\|no such file\|does not exist"; then
      HINTS="$HINTS
- **File not found**: A file or directory referenced in project.yml is missing. Check \`sources:\`, \`info:\`, and \`dependencies:\` paths."
    fi
    if echo "$XCODEGEN_ERR" | grep -qi "yaml\|parsing\|decode"; then
      HINTS="$HINTS
- **YAML parse error**: Check indentation and syntax in project.yml."
    fi
    if echo "$XCODEGEN_ERR" | grep -qi "target\|scheme"; then
      HINTS="$HINTS
- **Target/scheme error**: Check target names and dependency references."
    fi
    if echo "$XCODEGEN_ERR" | grep -qi "package\|dependency\|resolve"; then
      HINTS="$HINTS
- **Package error**: Check local package paths or remote package URLs."
    fi
    if [ -n "$HINTS" ]; then
      CAUSES="$CAUSES

### Detected Hints
$HINTS"
    fi

    fail_report "XcodeGen" \
      "\`xcodegen generate\` failed.

\`\`\`
$XCODEGEN_ERR
\`\`\`" \
      "$CAUSES" \
      "1. Read the error output above and fix project.yml
2. Run \`xcodegen generate\` manually to verify
3. Re-run \`./scripts/smoke-diagnostics.sh\`
4. If stuck, share \`build/smoke/xcodegen.log\` and \`project.yml\`"
  else
    log "xcodegen generate OK"
  fi
else
  log "No project.yml — using existing .xcodeproj"
fi

# --- 3. Xcode project check ---
log ""
log "--- Check: Xcode project ---"

if [ ! -d "$PROJECT_DIR/$PROJECT" ]; then
  fail_report "Xcode project" \
    "$PROJECT does not exist at $PROJECT_DIR/$PROJECT" \
    "- XcodeGen failed silently (check xcodegen.log)
- Project was not generated yet
- Wrong project name in script" \
    "Run \`xcodegen generate\` or verify project.yml target name matches \"$SCHEME\""
fi
log "Found $PROJECT"

log "Running: xcodebuild -list"
if ! xcodebuild -list -project "$PROJECT_DIR/$PROJECT" \
     > "$SMOKE_DIR/xcodebuild-list.log" 2>&1; then
  LIST_ERR=$(cat "$SMOKE_DIR/xcodebuild-list.log")
  log "xcodebuild -list FAILED"
  fail_report "xcodebuild -list" \
    "\`xcodebuild -list\` failed.

\`\`\`
$LIST_ERR
\`\`\`" \
    "- .xcodeproj is corrupted or incomplete
- XcodeGen produced an invalid project
- Xcode version mismatch with project format" \
    "1. Open $PROJECT in Xcode manually and check for errors
2. Try \`xcodegen generate\` again
3. Share \`build/smoke/xcodebuild-list.log\`"
fi

AVAILABLE_SCHEMES=$(grep -A 50 "Schemes:" "$SMOKE_DIR/xcodebuild-list.log" \
  | tail -n +2 | sed '/^$/q' | sed 's/^[[:space:]]*//' | grep -v '^$') || true
log "Available schemes: $AVAILABLE_SCHEMES"

if ! echo "$AVAILABLE_SCHEMES" | grep -q "^${SCHEME}$"; then
  fail_report "Scheme" \
    "Scheme \"$SCHEME\" not found in project.

Available schemes:
$AVAILABLE_SCHEMES" \
    "- Scheme name in project.yml does not match expected \"$SCHEME\"
- XcodeGen generated a different scheme name
- Scheme is not shared" \
    "Update SCHEME variable in this script, or fix project.yml"
fi
log "Scheme \"$SCHEME\" found"

# --- 4. Simulator check ---
log ""
log "--- Check: Simulator ---"

xcrun simctl list devices available > "$SMOKE_DIR/simulators.log" 2>&1 || true

BOOTED_UDID=$(xcrun simctl list devices booted -j 2>/dev/null \
  | python3 -c "
import json, sys
data = json.load(sys.stdin)
for runtime, devices in data.get('devices', {}).items():
    for d in devices:
        if d.get('state') == 'Booted':
            print(d['udid']); sys.exit(0)
sys.exit(1)
" 2>/dev/null) || true

if [ -z "$BOOTED_UDID" ]; then
  AVAILABLE_IPHONES=$(grep -i "iphone" "$SMOKE_DIR/simulators.log" | head -10) || true
  fail_report "Simulator" \
    "No booted simulator found." \
    "- Simulator app is not running
- No simulator device is booted" \
    "1. Open Simulator.app
2. Boot a device, or run:
   \`xcrun simctl boot \"iPhone 16 Pro\"\`

Available iPhone simulators:
\`\`\`
$AVAILABLE_IPHONES
\`\`\`"
fi

DEVICE_NAME=$(xcrun simctl list devices booted -j 2>/dev/null \
  | python3 -c "
import json, sys
data = json.load(sys.stdin)
for runtime, devices in data.get('devices', {}).items():
    for d in devices:
        if d.get('state') == 'Booted':
            print(d['name']); sys.exit(0)
") || true
log "Booted simulator: $DEVICE_NAME ($BOOTED_UDID)"

DESTINATION="platform=iOS Simulator,id=$BOOTED_UDID"

# --- Preflight summary ---
log ""
log "=== Preflight PASSED ==="
log "  Xcode:     $XCODEBUILD_VER"
log "  XcodeGen:  ${NEEDS_XCODEGEN:+required, OK}${NEEDS_XCODEGEN:+}$([ "$NEEDS_XCODEGEN" = false ] && echo 'not needed')"
log "  Project:   $PROJECT"
log "  Scheme:    $SCHEME"
log "  Simulator: $DEVICE_NAME ($BOOTED_UDID)"
log ""

{
  echo "# Preflight Passed"
  echo ""
  echo "| Check | Status |"
  echo "|-------|--------|"
  echo "| Xcode toolchain | $XCODEBUILD_VER |"
  if [ "$NEEDS_XCODEGEN" = true ]; then
    echo "| XcodeGen | $XCODEGEN_VER |"
    echo "| xcodegen generate | OK |"
  fi
  echo "| $PROJECT exists | OK |"
  echo "| xcodebuild -list | OK |"
  echo "| Scheme \"$SCHEME\" | Found |"
  echo "| Booted simulator | $DEVICE_NAME |"
  echo ""
  echo "---"
  echo "*Generated by smoke-diagnostics.sh at $(date)*"
} > "$SMOKE_DIR/preflight-report.md"

# ============================================================
# SMOKE DIAGNOSTICS PHASE
# ============================================================

MODE="${1:-full}"

case "$MODE" in
  preflight-only)
    log "=== preflight-only mode: stopping after preflight ==="
    echo ""
    echo "Preflight report: $SMOKE_DIR/preflight-report.md"
    exit 0
    ;;
  capture-only)
    log "=== Capture-only mode: skip build, capture screenshot + log ==="
    ;;
  full|"")
    log "=== Full mode: build, install, launch, capture ==="

    echo ""
    log "--- Build ---"
    xcodebuild build \
      -project "$PROJECT" \
      -scheme "$SCHEME" \
      -destination "$DESTINATION" \
      -configuration Debug \
      CODE_SIGNING_ALLOWED=NO \
      2>&1 | tee -a "$SMOKE_DIR/preflight.log" | tail -5

    echo ""
    log "--- Install ---"
    APP_PATH=$(find "$PROJECT_DIR/build" -name "Chapterly.app" -path "*/Debug-iphonesimulator/*" 2>/dev/null | head -1)
    if [ -z "$APP_PATH" ]; then
      APP_PATH=$(xcodebuild -project "$PROJECT" -scheme "$SCHEME" -showBuildSettings -configuration Debug \
        -destination "$DESTINATION" 2>/dev/null \
        | grep "BUILT_PRODUCTS_DIR" | head -1 | awk '{print $3}')
      APP_PATH="$APP_PATH/Chapterly.app"
    fi

    if [ ! -d "$APP_PATH" ]; then
      log "WARNING: Could not find built .app bundle. Trying to launch existing install."
    else
      xcrun simctl install "$BOOTED_UDID" "$APP_PATH"
      log "Installed $APP_PATH"
    fi

    echo ""
    log "--- Launch with --smoke-diagnostics ---"
    xcrun simctl terminate "$BOOTED_UDID" "$BUNDLE_ID" 2>/dev/null || true
    sleep 0.5
    xcrun simctl launch "$BOOTED_UDID" "$BUNDLE_ID" --smoke-diagnostics
    log "Launched with --smoke-diagnostics"
    sleep 3
    ;;
  *)
    echo "Usage: $0 [full|capture-only|preflight-only]"
    echo ""
    echo "  full            Build, install, launch, then capture (default)"
    echo "  capture-only    Skip build, capture screenshot + log from running app"
    echo "  preflight-only  Run preflight checks only, then stop"
    exit 1
    ;;
esac

echo ""
log "--- Capture screenshot ---"
xcrun simctl io "$BOOTED_UDID" screenshot "$SMOKE_DIR/current-screen.png" 2>/dev/null && \
  log "Screenshot: $SMOKE_DIR/current-screen.png" || \
  log "WARNING: Screenshot capture failed"

echo ""
log "--- Capture video (5 seconds) ---"
xcrun simctl io "$BOOTED_UDID" recordVideo --force "$SMOKE_DIR/current-run.mov" &
VIDEO_PID=$!
sleep 5
kill -INT "$VIDEO_PID" 2>/dev/null || true
wait "$VIDEO_PID" 2>/dev/null || true
log "Video: $SMOKE_DIR/current-run.mov"

echo ""
log "--- Collect app log ---"
xcrun simctl spawn "$BOOTED_UDID" log show \
  --predicate 'subsystem == "dev.chapterly" AND category == "smoke-diagnostics"' \
  --style compact \
  --last 2m \
  2>/dev/null > "$SMOKE_DIR/app.log" || true

SMOKE_LINES=$(grep -c "\[SMOKE\]" "$SMOKE_DIR/app.log" 2>/dev/null | tail -1 || echo "0")
SMOKE_LINES="${SMOKE_LINES:-0}"
log "Log: $SMOKE_DIR/app.log ($SMOKE_LINES [SMOKE] lines)"

echo ""
echo "=== Smoke Diagnostics Output ==="
echo ""
echo "  Preflight report:  $SMOKE_DIR/preflight-report.md"
echo "  Preflight log:     $SMOKE_DIR/preflight.log"
echo "  Screenshot:        $SMOKE_DIR/current-screen.png"
echo "  Video:             $SMOKE_DIR/current-run.mov"
echo "  App log:           $SMOKE_DIR/app.log"
if [ "$NEEDS_XCODEGEN" = true ]; then
  echo "  XcodeGen log:      $SMOKE_DIR/xcodegen.log"
fi
echo "  xcodebuild -list:  $SMOKE_DIR/xcodebuild-list.log"
echo "  Simulator list:    $SMOKE_DIR/simulators.log"
echo ""

if [ "$SMOKE_LINES" -gt 0 ]; then
  echo "--- Latest [SMOKE] entries ---"
  grep "\[SMOKE\]" "$SMOKE_DIR/app.log" | tail -20
else
  echo "No [SMOKE] log entries found. App may not have started with --smoke-diagnostics,"
  echo "or log entries were flushed. Try re-running in full mode."
fi

echo ""
echo "=== Done ==="
echo "Share these files for diagnosis:"
echo "  $SMOKE_DIR/preflight-report.md"
echo "  $SMOKE_DIR/current-screen.png"
echo "  $SMOKE_DIR/app.log"
